fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -
        id: end-of-file-fixer
        exclude: 'website/'
    -   id: check-toml
      #    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    # -   id: name-tests-test
    -   id: debug-statements

-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
    #   args:
    #   - --diff
    #   - --check

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        args:
        # - --diff
        # - --check
        - --profile=black

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-eradicate==1.4.0',
        'flake8-bugbear==22.9.23',
        'flake8-docstrings==1.6.0',
        'flake8-print==5.0.0',
        'pep8-naming==0.13.2',
      ]
      args:
        - "--config=setup.cfg"
-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.2
    hooks:
    -   id: pylint
        language: system
        files: ^(maxbot)/.*\.py$
        args:
          - --rcfile=setup.cfg
          #  run pylint across multiple cpu cores to speed it up-
          # https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
          - --jobs=0

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      additional_dependencies: ['.[toml]']
      args: [-c, pyproject.toml]

-   repo: local
    hooks:
    - id: unittests
      name: unittests
      stages: ["push"]
      entry: make test
      language: system
      always_run: True
      pass_filenames: false
